# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the mean of a numeric vector.
#'
#' @param x NumericVector of values.
#' @return The arithmetic mean of x.
meanC <- function(x) {
    .Call(`_rwavefetch_meanC`, x)
}

#' Identify coastal cells in a land matrix.
#'
#' This function examines each cell and its 3×3 neighborhood in the provided land matrix.
#' A cell is considered coastal if it is land (value 1) but not completely surrounded by land.
#'
#' @param land IntegerMatrix representing land (1) and water (0).
#' @return An IntegerMatrix with coastal cells marked as 1.
isitcoast <- function(land) {
    .Call(`_rwavefetch_isitcoast`, land)
}

#' Identify near-coast cells based on a land matrix and a search distance.
#'
#' For cells identified as coastal, this function marks surrounding water cells (value 0) 
#' within a distance dx as near-coast (value 2).
#'
#' @param land IntegerMatrix representing land (1) and water (0).
#' @param dx Integer specifying the search distance (in cells).
#' @return An IntegerMatrix with coastal cells marked as 1 and near-coast cells marked as 2.
isitnearcoast <- function(land, dx) {
    .Call(`_rwavefetch_isitnearcoast`, land, dx)
}

#' Compute the wind fetch metric using log-transformed distances.
#'
#' This function calculates a wind fetch metric (wx32) for coastal cells,
#' and uses a log-transformed approach for the random distance search.
#' An alternative mapping search is performed when the primary search is out-of-bound.
#'
#' The original name of this function was `coastwx32twomaplatlonf`
#'
#' @param land1 IntegerMatrix representing the primary land area.
#' @param land2 IntegerMatrix representing the secondary land area used for alternative mapping.
#' @param dx Integer specifying the search distance for near-coast detection.
#' @param dwx Integer controlling the magnitude of the random search distance.
#' @param cl Integer indicating the coastal cell class to process.
#' @param nsearches Integer specifying the number of iterations for the random search.
#' @param land1llx Double: lower left x-coordinate for land1.
#' @param land1uly Double: upper left y-coordinate for land1.
#' @param land1cellszx Double: cell size in the x-direction for land1.
#' @param land1cellszy Double: cell size in the y-direction for land1.
#' @param land2llx Double: lower left x-coordinate for land2.
#' @param land2uly Double: upper left y-coordinate for land2.
#' @param land2cellszx Double: cell size in the x-direction for land2.
#' @param land2cellszy Double: cell size in the y-direction for land2.
#' @param verbose Integer print messages to track progress. Use 0 for no messages, 1 for progress bar or 2 for text messages.
#' @return A NumericMatrix with the computed wind fetch metric based on the log-transformed search approach.
#' @export
coastal_wave_fetch <- function(land1, land2, dx, dwx, cl, jit, land1llx, land1uly, land1cellszx, land1cellszy, land2llx, land2uly, land2cellszx, land2cellszy, verbose = 1L) {
    .Call(`_rwavefetch_coastal_wave_fetch`, land1, land2, dx, dwx, cl, jit, land1llx, land1uly, land1cellszx, land1cellszy, land2llx, land2uly, land2cellszx, land2cellszy, verbose)
}

#' Compute the wind orientation metric using log-transformed distances.
#'
#' This function calculates a wind orientation metric (wx32) for coastal cells,
#' and uses a log-transformed approach for the random distance search.
#' An alternative mapping search is performed when the primary search is out-of-bound.
#'
#' The original name of this function was `coastwx32twomaplatlono`
#'
#' @param land1 IntegerMatrix representing the primary land area.
#' @param land2 IntegerMatrix representing the secondary land area used for alternative mapping.
#' @param dx Integer specifying the search distance for near-coast detection.
#' @param dwx Integer controlling the magnitude of the random search distance.
#' @param cl Integer indicating the coastal cell class to process.
#' @param nsearches Integer specifying the number of iterations for the random search.
#' @param land1llx Double: lower left x-coordinate for land1.
#' @param land1uly Double: upper left y-coordinate for land1.
#' @param land1cellszx Double: cell size in the x-direction for land1.
#' @param land1cellszy Double: cell size in the y-direction for land1.
#' @param land2llx Double: lower left x-coordinate for land2.
#' @param land2uly Double: upper left y-coordinate for land2.
#' @param land2cellszx Double: cell size in the x-direction for land2.
#' @param land2cellszy Double: cell size in the y-direction for land2.
#' @param verbose Integer print messages to track progress. Use 0 for no messages, 1 for progress bar or 2 for text messages.
#' @return A NumericMatrix with the computed wind fetch metric based on the log-transformed search approach.
#' @export
coastal_wave_orientation <- function(land1, land2, dx, dwx, cl, jit, land1llx, land1uly, land1cellszx, land1cellszy, land2llx, land2uly, land2cellszx, land2cellszy, verbose = 1L) {
    .Call(`_rwavefetch_coastal_wave_orientation`, land1, land2, dx, dwx, cl, jit, land1llx, land1uly, land1cellszx, land1cellszy, land2llx, land2uly, land2cellszx, land2cellszy, verbose)
}

#' Compute the wind fetch directionality using log-transformed distances.
#'
#' This function calculates a wind fetch metric (wx32) for coastal cells,
#' and uses a log-transformed approach for the random distance search.
#' An alternative mapping search is performed when the primary search is out-of-bound.
#'
#' The original name of this function was `coastwx32twomaplatlonv`
#'
#' @param land1 IntegerMatrix representing the primary land area.
#' @param land2 IntegerMatrix representing the secondary land area used for alternative mapping.
#' @param dx Integer specifying the search distance for near-coast detection.
#' @param dwx Integer controlling the magnitude of the random search distance.
#' @param cl Integer indicating the coastal cell class to process.
#' @param nsearches Integer specifying the number of iterations for the random search.
#' @param land1llx Double: lower left x-coordinate for land1.
#' @param land1uly Double: upper left y-coordinate for land1.
#' @param land1cellszx Double: cell size in the x-direction for land1.
#' @param land1cellszy Double: cell size in the y-direction for land1.
#' @param land2llx Double: lower left x-coordinate for land2.
#' @param land2uly Double: upper left y-coordinate for land2.
#' @param land2cellszx Double: cell size in the x-direction for land2.
#' @param land2cellszy Double: cell size in the y-direction for land2.
#' @param verbose Integer print messages to track progress. Use 0 for no messages, 1 for progress bar or 2 for text messages.
#' @return A NumericMatrix with the computed wind fetch metric based on the log-transformed search approach.
#' @export
coastal_wave_direction <- function(land1, land2, dx, dwx, cl, jit, land1llx, land1uly, land1cellszx, land1cellszy, land2llx, land2uly, land2cellszx, land2cellszy, verbose = 1L) {
    .Call(`_rwavefetch_coastal_wave_direction`, land1, land2, dx, dwx, cl, jit, land1llx, land1uly, land1cellszx, land1cellszy, land2llx, land2uly, land2cellszx, land2cellszy, verbose)
}

